/**
 * Reel asset path helpers.
 *
 * Each reel under /public/reels/<name>.mp4 has two derived assets generated by
 * the ffmpeg pass:
 *   • a short, muted, low-res preview loop at /reels/preview/<name>.mp4
 *     (used for autoplaying backgrounds — tiny + cheap to decode)
 *   • a poster frame at /reels/posters/<name>.jpg (instant first paint)
 *
 * The full file (/reels/<name>.mp4) is reserved for click-to-watch playback
 * (e.g. the portfolio lightbox), where quality + audio matter.
 */
export const reelPreview = (src: string): string => src.replace('/reels/', '/reels/preview/')

export const reelPoster = (src: string): string =>
  src.replace('/reels/', '/reels/posters/').replace(/\.mp4$/i, '.jpg')
