/**
 * Portfolio data — real Rogue Studio clients.
 *
 * Media comes from two places:
 *   • `reels` — local mp4s under /public/reels, with a preview loop and poster
 *     generated by the ffmpeg pass (see src/lib/reels.ts).
 *   • `bunnyMatch` — keys identifying this client's Bunny Stream uploads. The
 *     portfolio matches videos by title or description and attaches them
 *     automatically, so a new upload appears without a code change. Uploads are
 *     named after the client's Instagram handle (e.g. "averaclothing.in_178905…").
 *
 * Reels that resolve to nothing render as a "reel in the edit bay" placeholder —
 * never a broken player.
 *
 * Metrics policy: REAL numbers only, from client accounts or delivery records.
 * Where no figure exists we show qualitative `highlights` instead of inventing
 * percentages. Clients still being onboarded carry `needsContext` and roll in the
 * end credits rather than claiming a case study that hasn't happened yet.
 */

export type PortfolioTag =
  | 'Solar & Energy'
  | 'Spaces'
  | 'Fashion'
  | 'Finance'
  | 'Automotive'
  | 'In-House'

export interface Metric {
  value: string
  label: string
}

export interface PortfolioClient {
  id: string
  name: string
  slug: string
  logo: string
  /** Subtle glow / accent used behind the logo and on hover states. */
  accent: string
  industry: string
  tag: PortfolioTag
  instagram: string
  instagramHandle: string
  /** Short punchy line under the name. */
  tagline: string
  /** One-line summary of the engagement. */
  summary: string
  /** What we actually handle for them. */
  scope: string[]
  /** Longer narrative. */
  caseStudy: string
  /** REAL figures only. May be empty. */
  metrics: Metric[]
  /** Qualitative wins shown when metrics are sparse. */
  highlights: string[]
  /** Local mp4 reels (under /public/reels). */
  reels: string[]
  /**
   * Keys that identify this client's Bunny Stream videos — an upload-filename
   * prefix (usually their Instagram handle) or a Description tag. Several are
   * allowed: reposts upload under the original account's handle, and older
   * library entries are tagged by description rather than named after a handle.
   */
  bunnyMatch?: string[]
  /** Rogue's own subsidiary brand, not a paying client. */
  isInHouse?: boolean
  /** Engagement too new for a case study — rolls in the end credits instead. */
  needsContext?: boolean
}

export const PORTFOLIO_CLIENTS: PortfolioClient[] = [
  {
    id: 'sarvatra-energy',
    name: 'Sarvatra Energy',
    slug: 'sarvatra-energy',
    logo: '/clients/sarvatra.jpg',
    accent: '#f5a524',
    industry: 'Solar & Renewable Energy',
    tag: 'Solar & Energy',
    instagram: 'https://www.instagram.com/sarvatraenergy/',
    instagramHandle: '@sarvatraenergy',
    tagline: 'Founder-led content that sells solar.',
    summary:
      'With them since day one — building founder-led content and running performance ads that turn trust into qualified leads.',
    scope: ['Founder-Led Content', 'Brand Storytelling', 'Meta Ads Management', 'Lead Generation'],
    caseStudy:
      "We've been with Sarvatra from the very start of the brand. We built engaging, founder-led content that shows how they actually do business — the kind of transparency that builds real trust in a high-consideration purchase like solar. Alongside the content, we run their Meta ads end-to-end, consistently pulling qualified leads at under ₹15 each and returning roughly 10X on ad spend.",
    metrics: [
      { value: '10X', label: 'Return on ad spend' },
      { value: '<₹15', label: 'Cost per qualified lead' },
    ],
    highlights: ['Brand built from day one', 'Founder-led trust content', 'Qualified lead pipeline'],
    reels: ['/reels/sarvatra1.mp4', '/reels/sarvatra2.mp4', '/reels/sarvatra3.mp4'],
    bunnyMatch: ['Sarvatra Energy'],
  },
  {
    id: 'naman-vaastu',
    name: 'Naman Vaastu & Designs',
    slug: 'naman-vaastu',
    logo: '/clients/naman-vaastu.jpg',
    accent: '#c9a24b',
    industry: 'Architecture & Vaastu',
    tag: 'Spaces',
    instagram: 'https://www.instagram.com/namanvaastudesigns/',
    instagramHandle: '@namanvaastudesigns',
    tagline: 'One-stop studio. Script to lead.',
    summary:
      'A true one-stop engagement — personal branding for all three founders, on-site shoots, and Meta ads delivering 5X ROI.',
    scope: [
      'Personal Branding (×3 Founders)',
      'Client Testimonials',
      'On-Site Shoot Coverage',
      'Meta Ads & Lead Gen',
    ],
    caseStudy:
      'For Naman Vaastu we run the entire engine. We post consistent organic content across multiple pillars — personal branding for all three founders, captured client testimonials, and on-site shoot coverage from groundbreaking to completion. On top of that we manage their Meta ads and lead generation. From scripting to shooting to editing to posting to pushing ads, we own the full pipeline and deliver at least a 5X return.',
    metrics: [{ value: '5X', label: 'Minimum ROI delivered' }],
    highlights: [
      'Personal branding for 3 founders',
      'Client testimonial capture',
      'On-site shoot coverage',
      'Full script-to-lead pipeline',
    ],
    reels: [
      '/reels/naman1.mp4',
      '/reels/naman2.mp4',
      '/reels/naman3.mp4',
      '/reels/naman4.mp4',
      '/reels/interior1.mp4',
      '/reels/interior2.mp4',
      '/reels/interior3.mp4',
      '/reels/interior4.mp4',
    ],
    bunnyMatch: ['namanvaastudesigns', 'Naman Vaastu'],
  },
  {
    id: 'avera-clothing',
    name: 'Avera Clothing',
    slug: 'avera-clothing',
    logo: '/clients/avera-clothing.jpg',
    accent: '#f0b429',
    industry: 'Fashion & Apparel',
    tag: 'Fashion',
    instagram: 'https://www.instagram.com/averaclothing.in/',
    instagramHandle: '@averaclothing.in',
    tagline: 'Wear the sunshine.',
    summary: 'Short-form content production for a Jaipur apparel label.',
    scope: ['Content Production', 'Short-Form Video'],
    caseStudy:
      'Short-form content produced for Avera Clothing, a Jaipur apparel label. Three reels delivered so far — the clips in this scene are that work. Fuller case study once the campaign has numbers worth printing.',
    metrics: [],
    highlights: ['3 reels delivered', 'Jaipur apparel label'],
    reels: [],
    bunnyMatch: ['averaclothing.in'],
  },
  {
    id: 'kairos-atelier',
    name: 'Kairos Atelier',
    slug: 'kairos-atelier',
    logo: '/clients/kairos-atelier.jpg',
    accent: '#a63446',
    industry: 'Interiors & Design',
    tag: 'Spaces',
    instagram: 'https://www.instagram.com/kairos.atelier_/',
    instagramHandle: '@kairos.atelier_',
    tagline: 'Transforming spaces into timeless masterpieces.',
    summary: 'Short-form content production for an interiors and design studio.',
    scope: ['Content Production', 'Short-Form Video'],
    caseStudy:
      'Short-form content produced for Kairos Atelier, an interiors and design studio. Three reels delivered so far — the clips in this scene are that work. Fuller case study once the campaign has numbers worth printing.',
    metrics: [],
    highlights: ['3 reels delivered', 'Interiors & spaces'],
    reels: [],
    bunnyMatch: ['kairos.atelier_'],
  },
  {
    id: 'nikhil-shah',
    name: 'Nikhil Shah',
    slug: 'nikhil-shah',
    logo: '/clients/nikhil-shah.jpg',
    accent: '#2f6fed',
    industry: 'Finance & Investment',
    tag: 'Finance',
    instagram: 'https://www.instagram.com/finance.bynikhil/',
    instagramHandle: '@finance.bynikhil',
    tagline: 'Making finance easy for every Indian.',
    summary:
      'Founder-led personal-brand content for an AMFI-registered mutual fund distributor.',
    scope: ['Personal Branding', 'Short-Form Video'],
    caseStudy:
      'Personal-brand content produced for Nikhil Shah, an AMFI-registered mutual fund distributor — putting an advisor on camera in a category where trust is the whole product. Three reels delivered so far.',
    metrics: [],
    highlights: ['3 reels delivered', 'Founder-led personal brand'],
    reels: [],
    bunnyMatch: ['finance.bynikhil'],
  },
  {
    id: 'avni-fashion',
    name: 'Avni Fashion',
    slug: 'avni-fashion',
    logo: '/clients/avni-fashion.jpg',
    accent: '#e0538a',
    industry: 'Fashion & Apparel',
    tag: 'Fashion',
    instagram: 'https://www.instagram.com/avni_fashion_jaipur/',
    instagramHandle: '@avni_fashion_jaipur',
    tagline: 'Fashion content for Jaipur.',
    summary: 'Short-form content production for a Jaipur fashion label.',
    scope: ['Content Production', 'Short-Form Video'],
    caseStudy:
      'Short-form content produced for Avni Fashion, a Jaipur fashion label. Three reels delivered so far — the clips in this scene are that work. Fuller case study once the campaign has numbers worth printing.',
    metrics: [],
    highlights: ['3 reels delivered', 'Jaipur fashion label'],
    reels: [],
    bunnyMatch: ['avni_fashion_jaipur', 'smri.ti855'],
  },
  {
    id: 'shions',
    name: 'Shions',
    slug: 'shions',
    logo: '/clients/shions.jpg',
    accent: '#e8607f',
    industry: 'Fashion & Apparel',
    tag: 'Fashion',
    instagram: 'https://www.instagram.com/stylebyshions/',
    instagramHandle: '@stylebyshions',
    tagline: 'Style-led content.',
    summary: 'Short-form content production for a fashion and style brand.',
    scope: ['Content Production', 'Short-Form Video'],
    caseStudy:
      'Short-form content produced for Shions, a fashion and style brand. Three reels delivered so far — the clips in this scene are that work. Fuller case study once the campaign has numbers worth printing.',
    metrics: [],
    highlights: ['3 reels delivered', 'Style-led short-form'],
    reels: [],
    bunnyMatch: ['stylebyshions'],
  },
  {
    id: 'sira-collection',
    name: 'Sira Collection',
    slug: 'sira-collection',
    logo: '/clients/sira-collection.jpg',
    accent: '#d99b6c',
    industry: 'Fashion & Apparel',
    tag: 'Fashion',
    instagram: 'https://www.instagram.com/sira.collection._/',
    instagramHandle: '@sira.collection._',
    tagline: 'Sarees for every version of you.',
    summary: 'Short-form content production for a Jaipur saree label shipping across India.',
    scope: ['Content Production', 'Short-Form Video'],
    caseStudy:
      'Short-form content produced for Sira Collection, a Jaipur saree label shipping across India. First reel delivered, the rest in the edit bay.',
    metrics: [],
    highlights: ['1 reel delivered', 'More in production'],
    reels: [],
    bunnyMatch: ['sira.collection._'],
  },
  {
    id: 'secret-grapher',
    name: 'The Secret Grapher',
    slug: 'secret-grapher',
    logo: '/clients/secret-grapher.jpg',
    accent: '#d96a8f',
    industry: 'Wedding Films & Content',
    tag: 'In-House',
    instagram: 'https://www.instagram.com/the.secret.grapher/',
    instagramHandle: '@the.secret.grapher',
    tagline: 'Our wedding-content lab.',
    summary:
      'Rogue’s own subsidiary brand, dedicated to wedding films and content — with reels that have crossed millions of views.',
    scope: ['Wedding Films', 'Short-Form Content', 'Cinematic Storytelling'],
    caseStudy:
      'The Secret Grapher is our in-house subsidiary brand, focused entirely on wedding content and everything around it. It’s our proving ground for cinematic storytelling — home to some of our most-watched work, with reels that have crossed views in the millions.',
    metrics: [{ value: '1M+', label: 'Views on top reels' }],
    highlights: ['In-house subsidiary brand', 'Cinematic wedding films', 'Millions of views'],
    reels: [],
    isInHouse: true,
  },
  {
    id: 'shri-vinayak-car-decor',
    name: 'Shri Vinayak Car Decor',
    slug: 'shri-vinayak-car-decor',
    logo: '/clients/shri-vinayak.jpg',
    accent: '#d6453a',
    industry: 'Automotive Accessories',
    tag: 'Automotive',
    instagram: 'https://www.instagram.com/_shrivinayakcardecore_/',
    instagramHandle: '@_shrivinayakcardecore_',
    tagline: 'Car audio and accessories, Jaipur.',
    summary: 'Content engagement underway — first deliverables in production.',
    scope: ['Content Production'],
    caseStudy:
      'Content engagement for Shri Vinayak Car Decor, a Jaipur car audio and accessories retailer. First deliverables in production.',
    metrics: [],
    highlights: [],
    reels: [],
    bunnyMatch: ['_shrivinayakcardecore_'],
    needsContext: true,
  },
]

/* ── Resolved shapes (built in the server page after media resolution) ── */

export interface ResolvedReel {
  src: string
  available: boolean
}

export interface ResolvedClient extends Omit<PortfolioClient, 'reels'> {
  reels: ResolvedReel[]
  /** Count of reels that actually resolved to something playable. */
  liveReelCount: number
}

/** Lightbox payload. */
export interface ActiveReel {
  src: string
  client: string
  instagram: string
}
